# Generated by Django 3.2.13 on 2022-12-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file_name',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='sectiontimeslot',
            name='day',
            field=models.CharField(choices=[('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri')], default='Mon', max_length=3),
        ),
    ]
