# Generated by Django 3.2.13 on 2022-12-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20221201_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file_name',
            field=models.FileField(upload_to=None),
        ),
    ]
