# Generated by Django 3.2.13 on 2022-12-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_assignment_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffnotificationstudent',
            name='student_selected',
            field=models.BooleanField(default=False),
        ),
    ]
