# Generated by Django 3.2.13 on 2022-12-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_staffnotificationstudent_student_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='assignment1',
            field=models.TextField(default=0, verbose_name='Assignment 1'),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='assignment2',
            field=models.TextField(default=0, verbose_name='Assignment 2'),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='assignment3',
            field=models.TextField(default=0, verbose_name='Assignment 3'),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='assignment4',
            field=models.TextField(default=0, verbose_name='Assignment 4'),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='mid1',
            field=models.TextField(default=0, verbose_name='Mid 1'),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='mid2',
            field=models.TextField(default=0, verbose_name='Mid 2'),
        ),
    ]
