# Generated by Django 3.2.13 on 2022-12-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20221202_1804'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sectionstudents',
            constraint=models.UniqueConstraint(fields=('section', 'student'), name='unique_section_students'),
        ),
    ]
