# Generated by Django 3.2.13 on 2022-12-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_sectionstudents_unique_section_students'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sectiontimeslot',
            name='unique_timeslot',
        ),
        migrations.AddConstraint(
            model_name='sectiontimeslot',
            constraint=models.UniqueConstraint(fields=('timeslot', 'day'), name='unique_timeslot'),
        ),
    ]
