# Generated by Django 3.2.13 on 2022-12-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20221202_1937'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sectiontimeslot',
            name='unique_timeslot',
        ),
        migrations.AddConstraint(
            model_name='sectiontimeslot',
            constraint=models.UniqueConstraint(fields=('section', 'timeslot'), name='unique_timeslot'),
        ),
    ]
