# Generated by Django 3.2.13 on 2022-12-03 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20221202_1948'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sectiontimeslot',
            name='unique_timeslot',
        ),
    ]
